// Test wrapper: speccy with a generated test ROM, so the bus testbench has
// known contents to read back. Generated by the Makefile.

`default_nettype none

module speccy_tb_top (
    output wire        sd_cs,
    output wire        cpu_wait_n,
    output wire        _unused_sck_o,
    input  wire        clk,
    input  wire        rst,
    output wire        ce_cpu,
    output wire        ce_pix,

    input  wire [15:0] cpu_a,
    input  wire [7:0]  cpu_do,
    output wire [7:0]  cpu_di,
    input  wire        mreq_n,
    input  wire        iorq_n,
    input  wire        rd_n,
    input  wire        wr_n,
    input  wire        m1_n,
    output wire        int_n,

    input  wire        divmmc_en,
    input  wire        en_128,

    output wire [12:0] dram_addr,
    output wire [1:0]  dram_ba,
    input  wire [15:0] dram_dq_in,
    output wire [15:0] dram_dq_out,
    output wire        dram_dq_oe,
    output wire        dram_ldqm,
    output wire        dram_udqm,
    output wire        dram_ras_n,
    output wire        dram_cas_n,
    output wire        dram_we_n,
    output wire        dram_cs_n,
    output wire        dram_cke,

    input  wire [39:0] key_matrix,
    input  wire [4:0]  joy_state,
    input  wire        ear_in,
    output wire        speaker,
    output wire [9:0]  audio,
    output wire        mic,
    output wire [2:0]  border
);

    // sck deliberately unused: the loopback needs only data. Verilator is
    // right that it dangles, so give it a sink.
    wire sd_sck_w, sd_mosi_w;
    wire _unused_sck = sd_sck_w;

    speccy #(.ROM_FILE("sim/test_rom.hex"),
             .DIVMMC_ROM("sim/esx_rom.hex"),
             .ROM128_FILE("sim/rom128.hex")) u_speccy (
        .clk (clk), .rst (rst), .arm_snapshot (1'b0), .divmmc_en (divmmc_en),
        .en_128 (en_128),
        .dram_addr (dram_addr), .dram_ba (dram_ba),
        .dram_dq_in (dram_dq_in), .dram_dq_out (dram_dq_out),
        .dram_dq_oe (dram_dq_oe),
        .dram_ldqm (dram_ldqm), .dram_udqm (dram_udqm),
        .dram_ras_n (dram_ras_n), .dram_cas_n (dram_cas_n),
        .dram_we_n (dram_we_n), .dram_cs_n (dram_cs_n),
        .dram_cke (dram_cke),
        .boot_busy (), .cpu_wait_n (cpu_wait_n),
        .sd_cs (sd_cs), .sd_sck (sd_sck_w), .sd_mosi (sd_mosi_w),
        .sd_miso (sd_mosi_w),          // loopback: every exchange echoes
        .dbg_sd (),
        .ce_cpu (ce_cpu), .ce_pix (ce_pix),
        .cpu_a (cpu_a), .cpu_do (cpu_do), .cpu_di (cpu_di),
        .mreq_n (mreq_n), .iorq_n (iorq_n), .rd_n (rd_n), .wr_n (wr_n),
        .m1_n (m1_n), .int_n (int_n),
        .key_matrix (key_matrix), .joy_state (joy_state), .ear_in (ear_in),
        .ym_mode (1'b0), .audio (audio),
        .speaker (speaker), .mic (mic), .border (border),
        .vga_r (), .vga_g (), .vga_b (),
        .vga_hsync (), .vga_vsync (), .vga_blank ()
    );


    assign _unused_sck_o = _unused_sck;
endmodule

`default_nettype wire
