// Test wrapper: speccy with a generated test ROM, so the bus testbench has
// known contents to read back. Generated by the Makefile.

`default_nettype none

module speccy_tb_top (
    input  wire        clk,
    input  wire        rst,
    output wire        ce_cpu,
    output wire        ce_pix,

    input  wire [15:0] cpu_a,
    input  wire [7:0]  cpu_do,
    output wire [7:0]  cpu_di,
    input  wire        mreq_n,
    input  wire        iorq_n,
    input  wire        rd_n,
    input  wire        wr_n,
    input  wire        m1_n,
    output wire        int_n,

    input  wire [39:0] key_matrix,
    input  wire [4:0]  joy_state,
    input  wire        ear_in,
    output wire        speaker,
    output wire        mic,
    output wire [2:0]  border
);

    speccy #(.ROM_FILE("sim/test_rom.hex")) u_speccy (
        .clk (clk), .rst (rst), .ce_cpu (ce_cpu), .ce_pix (ce_pix),
        .cpu_a (cpu_a), .cpu_do (cpu_do), .cpu_di (cpu_di),
        .mreq_n (mreq_n), .iorq_n (iorq_n), .rd_n (rd_n), .wr_n (wr_n),
        .m1_n (m1_n), .int_n (int_n),
        .key_matrix (key_matrix), .joy_state (joy_state), .ear_in (ear_in),
        .speaker (speaker), .mic (mic), .border (border),
        .vga_r (), .vga_g (), .vga_b (),
        .vga_hsync (), .vga_vsync (), .vga_blank ()
    );

endmodule

`default_nettype wire
